@host = http://localhost:3000

###
GET {{host}}

###
POST {{host}}/blog
Content-Type: application/json

{
    "author": "john",
    "text": "i like traveling a lot!",
    "topic": "travel"
}

### 
GET {{host}}/blog

### 
GET {{host}}/blog/lilian

###
PUT {{host}}/blog/6374e72f4a81bd69cf8c3764
Content-Type: application/json

{
    "rating": 5
}

###
DELETE {{host}}/blog/6374e7334a81bd69cf8c3766